captainVersion: 4
services:
    $$cap_appname:
        image: m4dm4rtig4n/myelectricaldata:$$cap_myapp_version
        environment:
            TZ: Europe/Paris
        volumes:
            - $$cap_appname-data:/data
        caproverExtra:
            containerHttpPort: '5000'
caproverOneClickApp:
    variables:
        - id: $$cap_myapp_version
          label: MyElectricalData version
          defaultValue: '0.13.2'
          description: Check out their GitHub page for the valid tags https://github.com/MyElectricalData/myelectricaldata_import/releases
          validRegex: '/.{1,}/'
    instructions:
        start: |-
            MyElectricalData is official client for gateway MyElectricaData to import your electricity consumption from the officiel Enedis APIs.

            All data are import in local cache (SQLite) or external backend (PostgreSQL) which could then be exported to:

                MQTT
                Home Assistant (auto-discovery MQTT)
                InfluxDB
                PostgresSQL

            The tool also has APIs.
        end: |-
            Done!
            Create a `/var/lib/docker/volumes/captain--$$cap_appname-data/_data/config.yaml` with https://github.com/MyElectricalData/myelectricaldata_import/blob/main/config.example.yaml
            More documentation available here: https://github.com/MyElectricalData/myelectricaldata_import/wiki/03.-Configuration
            For Home Assistant integration see https://github.com/MyElectricalData/myelectricaldata_import/wiki/90.-Change-Log#home-assistant
    displayName: MyElectricalData
    isOfficial: true
    description: 📊 MyElectricalData is official client for gateway MyElectricaData to import your electricity consumption.
    documentation: This docker-compose is taken from https://github.com/MyElectricalData/myelectricaldata_import/wiki/02.-Installation#docker-compose
